[package]
name = "rgb-lib"
version = "0.2.0-alpha.2"
authors = ["Zoe Faltibà <zoefaltiba@gmail.com>", "Nicola Busanello <nicola.busanello@gmail.com>"]
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/RGB-Tools/rgb-lib"
homepage = "https://github.com/RGB-Tools/rgb-lib"
license = "MIT"
description = "RGB wallet library"
exclude = ["migration"]

[workspace]
members = [".", "migration"]

[dependencies]
base64 = "0.21.0"
bdk = { version = "0.28", features = ["electrum", "keys-bip39"] }
bitcoin = { version = "0.30.0", features = ["base64"] }
chacha20poly1305 = {version = "0.10.1", features = ["stream"]}
electrum-client = "0.15.1"
futures = "0.3"
hex = "0.4.3"
pbkdf2 = "0.12.0"
rand = "0.8.5"
rgb-lib-migration = { path = "migration", version = "0.2.0-alpha.2" }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "multipart", "native-tls"] }
scrypt = "0.11.0"
sea-orm = { version = "^0.11.3", features = ["sqlx-mysql", "sqlx-postgres", "sqlx-sqlite", "runtime-async-std-native-tls", "macros"] }
sea-query = "=0.28.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0", features = ["preserve_order"] }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
tempfile = "3.5.0"
thiserror = "1.0"
time = { version = "0.3.20", features = ["std"] }
tree_magic = "0.2.3"
typenum = "1.16.0"
walkdir = "2.3.3"
zip = { version = "0.6.6", default-features = false, features = ["time", "zstd"] }

# RGB-related deps
amplify = "=4.0.0"
bp-core = { version = "=0.10.5", features = ["serde"] }
bp-seals = "=0.10.5"
rgb-contracts = { version = "=0.10.0-rc.2", features = ["all", "electrum"] }
rgb-schemata = "=0.10.0-rc.1"
rgb-std = { version = "=0.10.3", features = ["all"] }
rgb-wallet = { version = "=0.10.3", features = ["all"] }
rgb_core = { package = "rgb-core", version = "=0.10.5" }
strict_encoding = "=2.5.0"
strict_types = "=1.5.0"

[dev-dependencies]
once_cell = "1.17.1"
tempfile = "3.5"
